version: '2.0'

services:
  rest-api:
    build:
      context: ./rest-api/.
      dockerfile: Dockerfile
    depends_on:
      - mongo-db
    environment:
      MONGO_HOST: mongo-db
    ports:
      - 8080:8080
    volumes:
      - ./rest-api/:/rest-api
      - /rest-api/node_modules
    command: wait-for-it mongo-db:27017 -t 30 -- npm start

  mongo-db:
    image: mongo
    restart: always